services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Anatolkin\ArpRestaurant\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/README.md'

  Anatolkin\ArpRestaurant\Backend\RecordLabel\RecordLabelProvider:
    public: true

  Anatolkin\ArpRestaurant\Backend\DataHandling\CopiedTranslationUuidHook:
    public: true
